name: Build and Deploy WASM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0             # otherwise, you will fail to push refs to dest repo

    - name: Set up Emscripten
      uses: mymindstorm/setup-emsdk@v14
      
    - name: Build WASM
      run: |
        cd rgfw_opengl2 && make CC=emcc
